version: '3.8'

services:
  ai-closet:
    build: .
    ports:
      - "19006:19006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_USE_DEV_SERVER=true
    stdin_open: true
    tty: true
    networks:
      - closet-network

networks:
  closet-network:
    driver: bridge

volumes:
  node_modules: